# fly.toml app configuration file generated for server-icy-snowflake-9033 on 2025-06-06T22:57:42+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "system32-misty-river-5136"
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
